Adds mouse features to [[https://neovim.io/][neovim]] using [[https://github.com/nvim-orgmode/orgmode][nvim-orgmode]].

Requires *neovim 0.9.2+*.

* Installation

  This plugin depends on [[https://github.com/nvim-orgmode/orgmode][nvim-orgmode/orgmode]].

** lazy.nvim (recommended)

   #+HTML: <details open>
   #+HTML: <summary>Code Example</summary>

   #+begin_src lua
   {
     "chipsenkbeil/org-mouse.nvim",
     dependencies = { "nvim-orgmode/orgmode" },
     config = function()
       require("org-mouse").setup()
     end
   }
   #+end_src

   #+HTML: </details>

** packer.nvim

   #+HTML: <details>
   #+HTML: <summary>Code Example</summary>

   #+begin_src lua
   use {
     "chipsenkbeil/org-mouse.nvim",
     requires = { "nvim-orgmode/orgmode" },
     config = function()
       require("org-mouse"):setup()
     end
   }
   #+end_src

   #+HTML: </details>
  
* Examples

** Link Highlighting by Hover

   TODO

** Navigating Links by Click

   TODO

* Configuration

** click_open_links
   
   If true, clicking on links will open them.

   Takes a boolean. Defaults to =true=.

   #+begin_src lua
   require("org-mouse"):setup({
     click_open_links = false,
   })
   #+end_src

** highlight_links
   
   If true, highlights links when mousing over them.
   
   This will enable =vim.opt.mouseoverevent= if disabled!

   Takes a boolean. Defaults to =true=.

   #+begin_src lua
   require("org-mouse"):setup({
     highlight_links = false,
   })
   #+end_src

** highlight_links_group
   
   Highlight group to apply when highlighting links.

   Takes a string. Defaults to =WarningMsg=.

   #+begin_src lua
   require("org-mouse"):setup({
     highlight_links_group = "Comment",
   })
   #+end_src

** filetypes
   
   Specifies filetypes where mouse events will be bound.

   This is leveraged during setup to configure a =FileType= autocmd to attach
   keybindings for =<MouseMove>= and =<LeftRelease>= to support mouse
   interactions.

   Takes a list of strings. Defaults to ={"org", "org-roam-*"}=.

   Notice that the strings are in pattern format, meaning you can use wildcards
   to support multiple filetypes.

   #+begin_src lua
   require("org-mouse"):setup({
     filetypes = { "org", "org-roam-*", "org-custom-*" },
   })
   #+end_src
